version: "3.8"

networks:
  Fire_Detection:
    name: Fire_Detection

services:
  rp_backend_service:
    image: rp_backend_image
    restart: always
    scale: 5
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - Fire_Detection
    depends_on:
      - minio
  
  mynginx:
    image: rp_mynginx_image
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - Fire_Detection
    depends_on:
      - rp_backend_service

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001" # pe acest port accesez interfata grafica
    networks:
      - Fire_Detection
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data